# Generated by Django 5.1.1 on 2024-10-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='user_type',
            field=models.CharField(default='client', max_length=20),
        ),
    ]
