# Generated by Django 5.1.1 on 2025-01-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
