# Generated by Django 5.1.1 on 2024-10-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MecanicienProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='prestataire', max_length=20)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_profil', models.ImageField(default='static/photos_profil/defaultProfil.jpg', upload_to='static/photos_profil/')),
                ('service', models.CharField(blank=True, choices=[('diagnostique', 'Diagnostique'), ('reparation_general', 'Réparation générale'), ('entretien_regulier', 'Entretien régulier')], max_length=50, null=True)),
                ('speciality', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('essence', 'Essence'), ('both', 'Les deux')], max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_message', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
