# Generated by Django 5.1.1 on 2024-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanicienprofile',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
