# Generated by Django 5.1.1 on 2024-10-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataire', '0002_alter_mecanicienprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanicienprofile',
            name='user_type',
            field=models.CharField(default='prestataire', max_length=20),
        ),
    ]
