# Generated by Django 5.1.1 on 2025-01-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataire', '0003_alter_mecanicienprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicienprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecanicienprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
